[project]
name = "ClipsToVideoMaker"
version = "0.1.0"
description = "Collect streamer clips and create video project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.14.0",
    "pandas>=2.3.3",
    "pywinauto>=0.6.9",
    "requests>=2.32.5",
    "twitchio>=3.1.0",
    "wmi>=1.5.1",
]
